// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package qux

// ServiceQuxBarClientNineOptions contains the optional parameters for the ServiceQuxBarClient.Nine method.
type ServiceQuxBarClientNineOptions struct {
	// placeholder for future optional parameters
}

// ServiceQuxClientEightOptions contains the optional parameters for the ServiceQuxClient.Eight method.
type ServiceQuxClientEightOptions struct {
	// placeholder for future optional parameters
}
