// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package fake

import (
	"context"
	"errors"
	"fmt"
	azfake "github.com/Azure/azure-sdk-for-go/sdk/azcore/fake"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/fake/server"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	"net/http"
	"uniongroup"
)

// UnionStringsOnlyServer is a fake server for instances of the uniongroup.UnionStringsOnlyClient type.
type UnionStringsOnlyServer struct {
	// Get is the fake for method UnionStringsOnlyClient.Get
	// HTTP status codes to indicate success: http.StatusOK
	Get func(ctx context.Context, options *uniongroup.UnionStringsOnlyClientGetOptions) (resp azfake.Responder[uniongroup.UnionStringsOnlyClientGetResponse], errResp azfake.ErrorResponder)

	// Send is the fake for method UnionStringsOnlyClient.Send
	// HTTP status codes to indicate success: http.StatusNoContent
	Send func(ctx context.Context, prop uniongroup.GetResponseProp5, options *uniongroup.UnionStringsOnlyClientSendOptions) (resp azfake.Responder[uniongroup.UnionStringsOnlyClientSendResponse], errResp azfake.ErrorResponder)
}

// NewUnionStringsOnlyServerTransport creates a new instance of UnionStringsOnlyServerTransport with the provided implementation.
// The returned UnionStringsOnlyServerTransport instance is connected to an instance of uniongroup.UnionStringsOnlyClient via the
// azcore.ClientOptions.Transporter field in the client's constructor parameters.
func NewUnionStringsOnlyServerTransport(srv *UnionStringsOnlyServer) *UnionStringsOnlyServerTransport {
	return &UnionStringsOnlyServerTransport{srv: srv}
}

// UnionStringsOnlyServerTransport connects instances of uniongroup.UnionStringsOnlyClient to instances of UnionStringsOnlyServer.
// Don't use this type directly, use NewUnionStringsOnlyServerTransport instead.
type UnionStringsOnlyServerTransport struct {
	srv *UnionStringsOnlyServer
}

// Do implements the policy.Transporter interface for UnionStringsOnlyServerTransport.
func (u *UnionStringsOnlyServerTransport) Do(req *http.Request) (*http.Response, error) {
	rawMethod := req.Context().Value(runtime.CtxAPINameKey{})
	method, ok := rawMethod.(string)
	if !ok {
		return nil, nonRetriableError{errors.New("unable to dispatch request, missing value for CtxAPINameKey")}
	}

	return u.dispatchToMethodFake(req, method)
}

func (u *UnionStringsOnlyServerTransport) dispatchToMethodFake(req *http.Request, method string) (*http.Response, error) {
	var resp *http.Response
	var err error

	switch method {
	case "UnionStringsOnlyClient.Get":
		resp, err = u.dispatchGet(req)
	case "UnionStringsOnlyClient.Send":
		resp, err = u.dispatchSend(req)
	default:
		err = fmt.Errorf("unhandled API %s", method)
	}

	return resp, err
}

func (u *UnionStringsOnlyServerTransport) dispatchGet(req *http.Request) (*http.Response, error) {
	if u.srv.Get == nil {
		return nil, &nonRetriableError{errors.New("fake for method Get not implemented")}
	}
	respr, errRespr := u.srv.Get(req.Context(), nil)
	if respErr := server.GetError(errRespr, req); respErr != nil {
		return nil, respErr
	}
	respContent := server.GetResponseContent(respr)
	if !contains([]int{http.StatusOK}, respContent.HTTPStatus) {
		return nil, &nonRetriableError{fmt.Errorf("unexpected status code %d. acceptable values are http.StatusOK", respContent.HTTPStatus)}
	}
	resp, err := server.MarshalResponseAsJSON(respContent, server.GetResponse(respr).GetResponse9, req)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (u *UnionStringsOnlyServerTransport) dispatchSend(req *http.Request) (*http.Response, error) {
	if u.srv.Send == nil {
		return nil, &nonRetriableError{errors.New("fake for method Send not implemented")}
	}
	type partialBodyParams struct {
		Prop GetResponseProp5 `json:"prop"`
	}
	body, err := server.UnmarshalRequestAsJSON[partialBodyParams](req)
	if err != nil {
		return nil, err
	}
	respr, errRespr := u.srv.Send(req.Context(), body.Prop, nil)
	if respErr := server.GetError(errRespr, req); respErr != nil {
		return nil, respErr
	}
	respContent := server.GetResponseContent(respr)
	if !contains([]int{http.StatusNoContent}, respContent.HTTPStatus) {
		return nil, &nonRetriableError{fmt.Errorf("unexpected status code %d. acceptable values are http.StatusNoContent", respContent.HTTPStatus)}
	}
	resp, err := server.NewResponse(respContent, req, nil)
	if err != nil {
		return nil, err
	}
	return resp, nil
}
