// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package file

// MultiPartFormDataFileClientUploadFileArrayOptions contains the optional parameters for the MultiPartFormDataFileClient.UploadFileArray
// method.
type MultiPartFormDataFileClientUploadFileArrayOptions struct {
	// placeholder for future optional parameters
}

// MultiPartFormDataFileClientUploadFileRequiredFilenameOptions contains the optional parameters for the MultiPartFormDataFileClient.UploadFileRequiredFilename
// method.
type MultiPartFormDataFileClientUploadFileRequiredFilenameOptions struct {
	// placeholder for future optional parameters
}

// MultiPartFormDataFileClientUploadFileSpecificContentTypeOptions contains the optional parameters for the MultiPartFormDataFileClient.UploadFileSpecificContentType
// method.
type MultiPartFormDataFileClientUploadFileSpecificContentTypeOptions struct {
	// placeholder for future optional parameters
}
