//go:build go1.18
// +build go1.18

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package lrodataplanegroup

type ErrorResponse struct {
	Code    *int32  `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

// LROsDataplaneClientBeginPostOplocSucceededOptions contains the optional parameters for the LROsDataplaneClient.BeginPostOplocSucceeded
// method.
type LROsDataplaneClientBeginPostOplocSucceededOptions struct {
	// Resumes the LRO from the provided token.
	ResumeToken string
}

type OperationResult struct {
	// the string value sent to the endpoint
	Value *string `json:"value,omitempty"`
}
