// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package shared

import "time"

// SharedMetadata - Common metadata shared across multiple services.
type SharedMetadata struct {
	// Creation timestamp of the resource.
	CreatedAt *time.Time

	// Creator of the resource.
	CreatedBy *string

	// Tags associated with the resource.
	Tags map[string]*string
}
