// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package modelproperties

type DictMethods struct {
	// REQUIRED
	Clear *string

	// REQUIRED
	Copy *string

	// REQUIRED
	Get *string

	// REQUIRED
	Items *string

	// REQUIRED
	Keys *string

	// REQUIRED
	Pop *string

	// REQUIRED
	Popitem *string

	// REQUIRED
	Setdefault *string

	// REQUIRED
	Update *string

	// REQUIRED
	Values *string
}

type ModelWithList struct {
	// REQUIRED
	List *string
}

type SameAsModel struct {
	// REQUIRED
	SameAsModel *string
}
