//go:build go1.18
// +build go1.18

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// DO NOT EDIT.

package additionalpropsgroup

import (
	"context"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/policy"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/tracing"
	"net/http"
)

// PetsClient contains the methods for the Pets group.
// Don't use this type directly, use a constructor function instead.
type PetsClient struct {
	internal *azcore.Client
}

// CreateAPInProperties - Create a Pet which contains more properties than what is defined.
// If the operation fails it returns an *azcore.ResponseError type.
//
// Generated from API version 1.0.0
//   - options - PetsClientCreateAPInPropertiesOptions contains the optional parameters for the PetsClient.CreateAPInProperties
//     method.
func (client *PetsClient) CreateAPInProperties(ctx context.Context, createParameters PetAPInProperties, options *PetsClientCreateAPInPropertiesOptions) (result PetsClientCreateAPInPropertiesResponse, err error) {
	ctx, span := client.internal.Tracer().Start(ctx, "PetsClient.CreateAPInProperties", &tracing.SpanOptions{
		Kind: tracing.SpanKindInternal,
	})
	defer func() {
		if err != nil {
			span.AddError(err)
		}
		span.End()
	}()
	req, err := client.createAPInPropertiesCreateRequest(ctx, createParameters, options)
	if err != nil {
		return
	}
	resp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return
	}
	if !runtime.HasStatusCode(resp, http.StatusOK) {
		err = runtime.NewResponseError(resp)
		return
	}
	result, err = client.createAPInPropertiesHandleResponse(resp)
	return
}

// createAPInPropertiesCreateRequest creates the CreateAPInProperties request.
func (client *PetsClient) createAPInPropertiesCreateRequest(ctx context.Context, createParameters PetAPInProperties, options *PetsClientCreateAPInPropertiesOptions) (*policy.Request, error) {
	urlPath := "/additionalProperties/in/properties"
	req, err := runtime.NewRequest(ctx, http.MethodPut, runtime.JoinPaths(host, urlPath))
	if err != nil {
		return nil, err
	}
	req.Raw().Header["Accept"] = []string{"application/json"}
	return req, runtime.MarshalAsJSON(req, createParameters)
}

// createAPInPropertiesHandleResponse handles the CreateAPInProperties response.
func (client *PetsClient) createAPInPropertiesHandleResponse(resp *http.Response) (result PetsClientCreateAPInPropertiesResponse, err error) {
	if err = runtime.UnmarshalAsJSON(resp, &result.PetAPInProperties); err != nil {
		result = PetsClientCreateAPInPropertiesResponse{}
		return
	}
	return result, nil
}

// CreateAPInPropertiesWithAPString - Create a Pet which contains more properties than what is defined.
// If the operation fails it returns an *azcore.ResponseError type.
//
// Generated from API version 1.0.0
//   - options - PetsClientCreateAPInPropertiesWithAPStringOptions contains the optional parameters for the PetsClient.CreateAPInPropertiesWithAPString
//     method.
func (client *PetsClient) CreateAPInPropertiesWithAPString(ctx context.Context, createParameters PetAPInPropertiesWithAPString, options *PetsClientCreateAPInPropertiesWithAPStringOptions) (result PetsClientCreateAPInPropertiesWithAPStringResponse, err error) {
	ctx, span := client.internal.Tracer().Start(ctx, "PetsClient.CreateAPInPropertiesWithAPString", &tracing.SpanOptions{
		Kind: tracing.SpanKindInternal,
	})
	defer func() {
		if err != nil {
			span.AddError(err)
		}
		span.End()
	}()
	req, err := client.createAPInPropertiesWithAPStringCreateRequest(ctx, createParameters, options)
	if err != nil {
		return
	}
	resp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return
	}
	if !runtime.HasStatusCode(resp, http.StatusOK) {
		err = runtime.NewResponseError(resp)
		return
	}
	result, err = client.createAPInPropertiesWithAPStringHandleResponse(resp)
	return
}

// createAPInPropertiesWithAPStringCreateRequest creates the CreateAPInPropertiesWithAPString request.
func (client *PetsClient) createAPInPropertiesWithAPStringCreateRequest(ctx context.Context, createParameters PetAPInPropertiesWithAPString, options *PetsClientCreateAPInPropertiesWithAPStringOptions) (*policy.Request, error) {
	urlPath := "/additionalProperties/in/properties/with/additionalProperties/string"
	req, err := runtime.NewRequest(ctx, http.MethodPut, runtime.JoinPaths(host, urlPath))
	if err != nil {
		return nil, err
	}
	req.Raw().Header["Accept"] = []string{"application/json"}
	return req, runtime.MarshalAsJSON(req, createParameters)
}

// createAPInPropertiesWithAPStringHandleResponse handles the CreateAPInPropertiesWithAPString response.
func (client *PetsClient) createAPInPropertiesWithAPStringHandleResponse(resp *http.Response) (result PetsClientCreateAPInPropertiesWithAPStringResponse, err error) {
	if err = runtime.UnmarshalAsJSON(resp, &result.PetAPInPropertiesWithAPString); err != nil {
		result = PetsClientCreateAPInPropertiesWithAPStringResponse{}
		return
	}
	return result, nil
}

// CreateAPObject - Create a Pet which contains more properties than what is defined.
// If the operation fails it returns an *azcore.ResponseError type.
//
// Generated from API version 1.0.0
//   - options - PetsClientCreateAPObjectOptions contains the optional parameters for the PetsClient.CreateAPObject method.
func (client *PetsClient) CreateAPObject(ctx context.Context, createParameters PetAPObject, options *PetsClientCreateAPObjectOptions) (result PetsClientCreateAPObjectResponse, err error) {
	ctx, span := client.internal.Tracer().Start(ctx, "PetsClient.CreateAPObject", &tracing.SpanOptions{
		Kind: tracing.SpanKindInternal,
	})
	defer func() {
		if err != nil {
			span.AddError(err)
		}
		span.End()
	}()
	req, err := client.createAPObjectCreateRequest(ctx, createParameters, options)
	if err != nil {
		return
	}
	resp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return
	}
	if !runtime.HasStatusCode(resp, http.StatusOK) {
		err = runtime.NewResponseError(resp)
		return
	}
	result, err = client.createAPObjectHandleResponse(resp)
	return
}

// createAPObjectCreateRequest creates the CreateAPObject request.
func (client *PetsClient) createAPObjectCreateRequest(ctx context.Context, createParameters PetAPObject, options *PetsClientCreateAPObjectOptions) (*policy.Request, error) {
	urlPath := "/additionalProperties/type/object"
	req, err := runtime.NewRequest(ctx, http.MethodPut, runtime.JoinPaths(host, urlPath))
	if err != nil {
		return nil, err
	}
	req.Raw().Header["Accept"] = []string{"application/json"}
	return req, runtime.MarshalAsJSON(req, createParameters)
}

// createAPObjectHandleResponse handles the CreateAPObject response.
func (client *PetsClient) createAPObjectHandleResponse(resp *http.Response) (result PetsClientCreateAPObjectResponse, err error) {
	if err = runtime.UnmarshalAsJSON(resp, &result.PetAPObject); err != nil {
		result = PetsClientCreateAPObjectResponse{}
		return
	}
	return result, nil
}

// CreateAPString - Create a Pet which contains more properties than what is defined.
// If the operation fails it returns an *azcore.ResponseError type.
//
// Generated from API version 1.0.0
//   - options - PetsClientCreateAPStringOptions contains the optional parameters for the PetsClient.CreateAPString method.
func (client *PetsClient) CreateAPString(ctx context.Context, createParameters PetAPString, options *PetsClientCreateAPStringOptions) (result PetsClientCreateAPStringResponse, err error) {
	ctx, span := client.internal.Tracer().Start(ctx, "PetsClient.CreateAPString", &tracing.SpanOptions{
		Kind: tracing.SpanKindInternal,
	})
	defer func() {
		if err != nil {
			span.AddError(err)
		}
		span.End()
	}()
	req, err := client.createAPStringCreateRequest(ctx, createParameters, options)
	if err != nil {
		return
	}
	resp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return
	}
	if !runtime.HasStatusCode(resp, http.StatusOK) {
		err = runtime.NewResponseError(resp)
		return
	}
	result, err = client.createAPStringHandleResponse(resp)
	return
}

// createAPStringCreateRequest creates the CreateAPString request.
func (client *PetsClient) createAPStringCreateRequest(ctx context.Context, createParameters PetAPString, options *PetsClientCreateAPStringOptions) (*policy.Request, error) {
	urlPath := "/additionalProperties/type/string"
	req, err := runtime.NewRequest(ctx, http.MethodPut, runtime.JoinPaths(host, urlPath))
	if err != nil {
		return nil, err
	}
	req.Raw().Header["Accept"] = []string{"application/json"}
	return req, runtime.MarshalAsJSON(req, createParameters)
}

// createAPStringHandleResponse handles the CreateAPString response.
func (client *PetsClient) createAPStringHandleResponse(resp *http.Response) (result PetsClientCreateAPStringResponse, err error) {
	if err = runtime.UnmarshalAsJSON(resp, &result.PetAPString); err != nil {
		result = PetsClientCreateAPStringResponse{}
		return
	}
	return result, nil
}

// CreateAPTrue - Create a Pet which contains more properties than what is defined.
// If the operation fails it returns an *azcore.ResponseError type.
//
// Generated from API version 1.0.0
//   - options - PetsClientCreateAPTrueOptions contains the optional parameters for the PetsClient.CreateAPTrue method.
func (client *PetsClient) CreateAPTrue(ctx context.Context, createParameters PetAPTrue, options *PetsClientCreateAPTrueOptions) (result PetsClientCreateAPTrueResponse, err error) {
	ctx, span := client.internal.Tracer().Start(ctx, "PetsClient.CreateAPTrue", &tracing.SpanOptions{
		Kind: tracing.SpanKindInternal,
	})
	defer func() {
		if err != nil {
			span.AddError(err)
		}
		span.End()
	}()
	req, err := client.createAPTrueCreateRequest(ctx, createParameters, options)
	if err != nil {
		return
	}
	resp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return
	}
	if !runtime.HasStatusCode(resp, http.StatusOK) {
		err = runtime.NewResponseError(resp)
		return
	}
	result, err = client.createAPTrueHandleResponse(resp)
	return
}

// createAPTrueCreateRequest creates the CreateAPTrue request.
func (client *PetsClient) createAPTrueCreateRequest(ctx context.Context, createParameters PetAPTrue, options *PetsClientCreateAPTrueOptions) (*policy.Request, error) {
	urlPath := "/additionalProperties/true"
	req, err := runtime.NewRequest(ctx, http.MethodPut, runtime.JoinPaths(host, urlPath))
	if err != nil {
		return nil, err
	}
	req.Raw().Header["Accept"] = []string{"application/json"}
	return req, runtime.MarshalAsJSON(req, createParameters)
}

// createAPTrueHandleResponse handles the CreateAPTrue response.
func (client *PetsClient) createAPTrueHandleResponse(resp *http.Response) (result PetsClientCreateAPTrueResponse, err error) {
	if err = runtime.UnmarshalAsJSON(resp, &result.PetAPTrue); err != nil {
		result = PetsClientCreateAPTrueResponse{}
		return
	}
	return result, nil
}

// CreateCatAPTrue - Create a CatAPTrue which contains more properties than what is defined.
// If the operation fails it returns an *azcore.ResponseError type.
//
// Generated from API version 1.0.0
//   - options - PetsClientCreateCatAPTrueOptions contains the optional parameters for the PetsClient.CreateCatAPTrue method.
func (client *PetsClient) CreateCatAPTrue(ctx context.Context, createParameters CatAPTrue, options *PetsClientCreateCatAPTrueOptions) (result PetsClientCreateCatAPTrueResponse, err error) {
	ctx, span := client.internal.Tracer().Start(ctx, "PetsClient.CreateCatAPTrue", &tracing.SpanOptions{
		Kind: tracing.SpanKindInternal,
	})
	defer func() {
		if err != nil {
			span.AddError(err)
		}
		span.End()
	}()
	req, err := client.createCatAPTrueCreateRequest(ctx, createParameters, options)
	if err != nil {
		return
	}
	resp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return
	}
	if !runtime.HasStatusCode(resp, http.StatusOK) {
		err = runtime.NewResponseError(resp)
		return
	}
	result, err = client.createCatAPTrueHandleResponse(resp)
	return
}

// createCatAPTrueCreateRequest creates the CreateCatAPTrue request.
func (client *PetsClient) createCatAPTrueCreateRequest(ctx context.Context, createParameters CatAPTrue, options *PetsClientCreateCatAPTrueOptions) (*policy.Request, error) {
	urlPath := "/additionalProperties/true-subclass"
	req, err := runtime.NewRequest(ctx, http.MethodPut, runtime.JoinPaths(host, urlPath))
	if err != nil {
		return nil, err
	}
	req.Raw().Header["Accept"] = []string{"application/json"}
	return req, runtime.MarshalAsJSON(req, createParameters)
}

// createCatAPTrueHandleResponse handles the CreateCatAPTrue response.
func (client *PetsClient) createCatAPTrueHandleResponse(resp *http.Response) (result PetsClientCreateCatAPTrueResponse, err error) {
	if err = runtime.UnmarshalAsJSON(resp, &result.CatAPTrue); err != nil {
		result = PetsClientCreateCatAPTrueResponse{}
		return
	}
	return result, nil
}
