// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package fake

import (
	"errors"
	"fmt"
	azfake "github.com/Azure/azure-sdk-for-go/sdk/azcore/fake"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/fake/server"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	"net/http"
	"pageablegroup/serverdrivenpagination/continuationtoken"
	"slices"
)

// PageableServerDrivenPaginationContinuationTokenServer is a fake server for instances of the continuationtoken.PageableServerDrivenPaginationContinuationTokenClient type.
type PageableServerDrivenPaginationContinuationTokenServer struct {
	// NewRequestHeaderNestedResponseBodyPager is the fake for method PageableServerDrivenPaginationContinuationTokenClient.NewRequestHeaderNestedResponseBodyPager
	// HTTP status codes to indicate success: http.StatusOK
	NewRequestHeaderNestedResponseBodyPager func(options *continuationtoken.PageableServerDrivenPaginationContinuationTokenClientRequestHeaderNestedResponseBodyOptions) (resp azfake.PagerResponder[continuationtoken.PageableServerDrivenPaginationContinuationTokenClientRequestHeaderNestedResponseBodyResponse])

	// NewRequestHeaderResponseBodyPager is the fake for method PageableServerDrivenPaginationContinuationTokenClient.NewRequestHeaderResponseBodyPager
	// HTTP status codes to indicate success: http.StatusOK
	NewRequestHeaderResponseBodyPager func(options *continuationtoken.PageableServerDrivenPaginationContinuationTokenClientRequestHeaderResponseBodyOptions) (resp azfake.PagerResponder[continuationtoken.PageableServerDrivenPaginationContinuationTokenClientRequestHeaderResponseBodyResponse])

	// NewRequestHeaderResponseHeaderPager is the fake for method PageableServerDrivenPaginationContinuationTokenClient.NewRequestHeaderResponseHeaderPager
	// HTTP status codes to indicate success: http.StatusOK
	NewRequestHeaderResponseHeaderPager func(options *continuationtoken.PageableServerDrivenPaginationContinuationTokenClientRequestHeaderResponseHeaderOptions) (resp azfake.PagerResponder[continuationtoken.PageableServerDrivenPaginationContinuationTokenClientRequestHeaderResponseHeaderResponse])

	// NewRequestQueryNestedResponseBodyPager is the fake for method PageableServerDrivenPaginationContinuationTokenClient.NewRequestQueryNestedResponseBodyPager
	// HTTP status codes to indicate success: http.StatusOK
	NewRequestQueryNestedResponseBodyPager func(options *continuationtoken.PageableServerDrivenPaginationContinuationTokenClientRequestQueryNestedResponseBodyOptions) (resp azfake.PagerResponder[continuationtoken.PageableServerDrivenPaginationContinuationTokenClientRequestQueryNestedResponseBodyResponse])

	// NewRequestQueryResponseBodyPager is the fake for method PageableServerDrivenPaginationContinuationTokenClient.NewRequestQueryResponseBodyPager
	// HTTP status codes to indicate success: http.StatusOK
	NewRequestQueryResponseBodyPager func(options *continuationtoken.PageableServerDrivenPaginationContinuationTokenClientRequestQueryResponseBodyOptions) (resp azfake.PagerResponder[continuationtoken.PageableServerDrivenPaginationContinuationTokenClientRequestQueryResponseBodyResponse])

	// NewRequestQueryResponseHeaderPager is the fake for method PageableServerDrivenPaginationContinuationTokenClient.NewRequestQueryResponseHeaderPager
	// HTTP status codes to indicate success: http.StatusOK
	NewRequestQueryResponseHeaderPager func(options *continuationtoken.PageableServerDrivenPaginationContinuationTokenClientRequestQueryResponseHeaderOptions) (resp azfake.PagerResponder[continuationtoken.PageableServerDrivenPaginationContinuationTokenClientRequestQueryResponseHeaderResponse])
}

// NewPageableServerDrivenPaginationContinuationTokenServerTransport creates a new instance of PageableServerDrivenPaginationContinuationTokenServerTransport with the provided implementation.
// The returned PageableServerDrivenPaginationContinuationTokenServerTransport instance is connected to an instance of continuationtoken.PageableServerDrivenPaginationContinuationTokenClient via the
// azcore.ClientOptions.Transporter field in the client's constructor parameters.
func NewPageableServerDrivenPaginationContinuationTokenServerTransport(srv *PageableServerDrivenPaginationContinuationTokenServer) *PageableServerDrivenPaginationContinuationTokenServerTransport {
	return &PageableServerDrivenPaginationContinuationTokenServerTransport{
		srv:                                     srv,
		newRequestHeaderNestedResponseBodyPager: newTracker[azfake.PagerResponder[continuationtoken.PageableServerDrivenPaginationContinuationTokenClientRequestHeaderNestedResponseBodyResponse]](),
		newRequestHeaderResponseBodyPager:       newTracker[azfake.PagerResponder[continuationtoken.PageableServerDrivenPaginationContinuationTokenClientRequestHeaderResponseBodyResponse]](),
		newRequestHeaderResponseHeaderPager:     newTracker[azfake.PagerResponder[continuationtoken.PageableServerDrivenPaginationContinuationTokenClientRequestHeaderResponseHeaderResponse]](),
		newRequestQueryNestedResponseBodyPager:  newTracker[azfake.PagerResponder[continuationtoken.PageableServerDrivenPaginationContinuationTokenClientRequestQueryNestedResponseBodyResponse]](),
		newRequestQueryResponseBodyPager:        newTracker[azfake.PagerResponder[continuationtoken.PageableServerDrivenPaginationContinuationTokenClientRequestQueryResponseBodyResponse]](),
		newRequestQueryResponseHeaderPager:      newTracker[azfake.PagerResponder[continuationtoken.PageableServerDrivenPaginationContinuationTokenClientRequestQueryResponseHeaderResponse]](),
	}
}

// PageableServerDrivenPaginationContinuationTokenServerTransport connects instances of continuationtoken.PageableServerDrivenPaginationContinuationTokenClient to instances of PageableServerDrivenPaginationContinuationTokenServer.
// Don't use this type directly, use NewPageableServerDrivenPaginationContinuationTokenServerTransport instead.
type PageableServerDrivenPaginationContinuationTokenServerTransport struct {
	srv                                     *PageableServerDrivenPaginationContinuationTokenServer
	newRequestHeaderNestedResponseBodyPager *tracker[azfake.PagerResponder[continuationtoken.PageableServerDrivenPaginationContinuationTokenClientRequestHeaderNestedResponseBodyResponse]]
	newRequestHeaderResponseBodyPager       *tracker[azfake.PagerResponder[continuationtoken.PageableServerDrivenPaginationContinuationTokenClientRequestHeaderResponseBodyResponse]]
	newRequestHeaderResponseHeaderPager     *tracker[azfake.PagerResponder[continuationtoken.PageableServerDrivenPaginationContinuationTokenClientRequestHeaderResponseHeaderResponse]]
	newRequestQueryNestedResponseBodyPager  *tracker[azfake.PagerResponder[continuationtoken.PageableServerDrivenPaginationContinuationTokenClientRequestQueryNestedResponseBodyResponse]]
	newRequestQueryResponseBodyPager        *tracker[azfake.PagerResponder[continuationtoken.PageableServerDrivenPaginationContinuationTokenClientRequestQueryResponseBodyResponse]]
	newRequestQueryResponseHeaderPager      *tracker[azfake.PagerResponder[continuationtoken.PageableServerDrivenPaginationContinuationTokenClientRequestQueryResponseHeaderResponse]]
}

// Do implements the policy.Transporter interface for PageableServerDrivenPaginationContinuationTokenServerTransport.
func (p *PageableServerDrivenPaginationContinuationTokenServerTransport) Do(req *http.Request) (*http.Response, error) {
	rawMethod := req.Context().Value(runtime.CtxAPINameKey{})
	method, ok := rawMethod.(string)
	if !ok {
		return nil, nonRetriableError{errors.New("unable to dispatch request, missing value for CtxAPINameKey")}
	}

	return p.dispatchToMethodFake(req, method)
}

func (p *PageableServerDrivenPaginationContinuationTokenServerTransport) dispatchToMethodFake(req *http.Request, method string) (*http.Response, error) {
	resultChan := make(chan result, 1)
	go func() {
		var intercepted bool
		var res result
		if pageableServerDrivenPaginationContinuationTokenServerTransportInterceptor != nil {
			res.resp, res.err, intercepted = pageableServerDrivenPaginationContinuationTokenServerTransportInterceptor.Do(req)
		}
		if !intercepted {
			switch method {
			case "PageableServerDrivenPaginationContinuationTokenClient.NewRequestHeaderNestedResponseBodyPager":
				res.resp, res.err = p.dispatchNewRequestHeaderNestedResponseBodyPager(req)
			case "PageableServerDrivenPaginationContinuationTokenClient.NewRequestHeaderResponseBodyPager":
				res.resp, res.err = p.dispatchNewRequestHeaderResponseBodyPager(req)
			case "PageableServerDrivenPaginationContinuationTokenClient.NewRequestHeaderResponseHeaderPager":
				res.resp, res.err = p.dispatchNewRequestHeaderResponseHeaderPager(req)
			case "PageableServerDrivenPaginationContinuationTokenClient.NewRequestQueryNestedResponseBodyPager":
				res.resp, res.err = p.dispatchNewRequestQueryNestedResponseBodyPager(req)
			case "PageableServerDrivenPaginationContinuationTokenClient.NewRequestQueryResponseBodyPager":
				res.resp, res.err = p.dispatchNewRequestQueryResponseBodyPager(req)
			case "PageableServerDrivenPaginationContinuationTokenClient.NewRequestQueryResponseHeaderPager":
				res.resp, res.err = p.dispatchNewRequestQueryResponseHeaderPager(req)
			default:
				res.err = fmt.Errorf("unhandled API %s", method)
			}

		}
		resultChan <- res
	}()

	select {
	case <-req.Context().Done():
		return nil, req.Context().Err()
	case res := <-resultChan:
		return res.resp, res.err
	}
}

func (p *PageableServerDrivenPaginationContinuationTokenServerTransport) dispatchNewRequestHeaderNestedResponseBodyPager(req *http.Request) (*http.Response, error) {
	if p.srv.NewRequestHeaderNestedResponseBodyPager == nil {
		return nil, &nonRetriableError{errors.New("fake for method NewRequestHeaderNestedResponseBodyPager not implemented")}
	}
	newRequestHeaderNestedResponseBodyPager := p.newRequestHeaderNestedResponseBodyPager.get(req)
	if newRequestHeaderNestedResponseBodyPager == nil {
		qp := req.URL.Query()
		tokenParam := getOptional(getHeaderValue(req.Header, "token"))
		fooParam := getOptional(getHeaderValue(req.Header, "foo"))
		barParam := getOptional(qp.Get("bar"))
		var options *continuationtoken.PageableServerDrivenPaginationContinuationTokenClientRequestHeaderNestedResponseBodyOptions
		if tokenParam != nil || fooParam != nil || barParam != nil {
			options = &continuationtoken.PageableServerDrivenPaginationContinuationTokenClientRequestHeaderNestedResponseBodyOptions{
				Token: tokenParam,
				Foo:   fooParam,
				Bar:   barParam,
			}
		}
		resp := p.srv.NewRequestHeaderNestedResponseBodyPager(options)
		newRequestHeaderNestedResponseBodyPager = &resp
		p.newRequestHeaderNestedResponseBodyPager.add(req, newRequestHeaderNestedResponseBodyPager)
	}
	resp, err := server.PagerResponderNext(newRequestHeaderNestedResponseBodyPager, req)
	if err != nil {
		return nil, err
	}
	if !slices.Contains([]int{http.StatusOK}, resp.StatusCode) {
		p.newRequestHeaderNestedResponseBodyPager.remove(req)
		return nil, &nonRetriableError{fmt.Errorf("unexpected status code %d. acceptable values are http.StatusOK", resp.StatusCode)}
	}
	if !server.PagerResponderMore(newRequestHeaderNestedResponseBodyPager) {
		p.newRequestHeaderNestedResponseBodyPager.remove(req)
	}
	return resp, nil
}

func (p *PageableServerDrivenPaginationContinuationTokenServerTransport) dispatchNewRequestHeaderResponseBodyPager(req *http.Request) (*http.Response, error) {
	if p.srv.NewRequestHeaderResponseBodyPager == nil {
		return nil, &nonRetriableError{errors.New("fake for method NewRequestHeaderResponseBodyPager not implemented")}
	}
	newRequestHeaderResponseBodyPager := p.newRequestHeaderResponseBodyPager.get(req)
	if newRequestHeaderResponseBodyPager == nil {
		qp := req.URL.Query()
		tokenParam := getOptional(getHeaderValue(req.Header, "token"))
		fooParam := getOptional(getHeaderValue(req.Header, "foo"))
		barParam := getOptional(qp.Get("bar"))
		var options *continuationtoken.PageableServerDrivenPaginationContinuationTokenClientRequestHeaderResponseBodyOptions
		if tokenParam != nil || fooParam != nil || barParam != nil {
			options = &continuationtoken.PageableServerDrivenPaginationContinuationTokenClientRequestHeaderResponseBodyOptions{
				Token: tokenParam,
				Foo:   fooParam,
				Bar:   barParam,
			}
		}
		resp := p.srv.NewRequestHeaderResponseBodyPager(options)
		newRequestHeaderResponseBodyPager = &resp
		p.newRequestHeaderResponseBodyPager.add(req, newRequestHeaderResponseBodyPager)
	}
	resp, err := server.PagerResponderNext(newRequestHeaderResponseBodyPager, req)
	if err != nil {
		return nil, err
	}
	if !slices.Contains([]int{http.StatusOK}, resp.StatusCode) {
		p.newRequestHeaderResponseBodyPager.remove(req)
		return nil, &nonRetriableError{fmt.Errorf("unexpected status code %d. acceptable values are http.StatusOK", resp.StatusCode)}
	}
	if !server.PagerResponderMore(newRequestHeaderResponseBodyPager) {
		p.newRequestHeaderResponseBodyPager.remove(req)
	}
	return resp, nil
}

func (p *PageableServerDrivenPaginationContinuationTokenServerTransport) dispatchNewRequestHeaderResponseHeaderPager(req *http.Request) (*http.Response, error) {
	if p.srv.NewRequestHeaderResponseHeaderPager == nil {
		return nil, &nonRetriableError{errors.New("fake for method NewRequestHeaderResponseHeaderPager not implemented")}
	}
	newRequestHeaderResponseHeaderPager := p.newRequestHeaderResponseHeaderPager.get(req)
	if newRequestHeaderResponseHeaderPager == nil {
		qp := req.URL.Query()
		tokenParam := getOptional(getHeaderValue(req.Header, "token"))
		fooParam := getOptional(getHeaderValue(req.Header, "foo"))
		barParam := getOptional(qp.Get("bar"))
		var options *continuationtoken.PageableServerDrivenPaginationContinuationTokenClientRequestHeaderResponseHeaderOptions
		if tokenParam != nil || fooParam != nil || barParam != nil {
			options = &continuationtoken.PageableServerDrivenPaginationContinuationTokenClientRequestHeaderResponseHeaderOptions{
				Token: tokenParam,
				Foo:   fooParam,
				Bar:   barParam,
			}
		}
		resp := p.srv.NewRequestHeaderResponseHeaderPager(options)
		newRequestHeaderResponseHeaderPager = &resp
		p.newRequestHeaderResponseHeaderPager.add(req, newRequestHeaderResponseHeaderPager)
	}
	resp, err := server.PagerResponderNext(newRequestHeaderResponseHeaderPager, req)
	if err != nil {
		return nil, err
	}
	if !slices.Contains([]int{http.StatusOK}, resp.StatusCode) {
		p.newRequestHeaderResponseHeaderPager.remove(req)
		return nil, &nonRetriableError{fmt.Errorf("unexpected status code %d. acceptable values are http.StatusOK", resp.StatusCode)}
	}
	if !server.PagerResponderMore(newRequestHeaderResponseHeaderPager) {
		p.newRequestHeaderResponseHeaderPager.remove(req)
	}
	return resp, nil
}

func (p *PageableServerDrivenPaginationContinuationTokenServerTransport) dispatchNewRequestQueryNestedResponseBodyPager(req *http.Request) (*http.Response, error) {
	if p.srv.NewRequestQueryNestedResponseBodyPager == nil {
		return nil, &nonRetriableError{errors.New("fake for method NewRequestQueryNestedResponseBodyPager not implemented")}
	}
	newRequestQueryNestedResponseBodyPager := p.newRequestQueryNestedResponseBodyPager.get(req)
	if newRequestQueryNestedResponseBodyPager == nil {
		qp := req.URL.Query()
		tokenParam := getOptional(qp.Get("token"))
		fooParam := getOptional(getHeaderValue(req.Header, "foo"))
		barParam := getOptional(qp.Get("bar"))
		var options *continuationtoken.PageableServerDrivenPaginationContinuationTokenClientRequestQueryNestedResponseBodyOptions
		if tokenParam != nil || fooParam != nil || barParam != nil {
			options = &continuationtoken.PageableServerDrivenPaginationContinuationTokenClientRequestQueryNestedResponseBodyOptions{
				Token: tokenParam,
				Foo:   fooParam,
				Bar:   barParam,
			}
		}
		resp := p.srv.NewRequestQueryNestedResponseBodyPager(options)
		newRequestQueryNestedResponseBodyPager = &resp
		p.newRequestQueryNestedResponseBodyPager.add(req, newRequestQueryNestedResponseBodyPager)
	}
	resp, err := server.PagerResponderNext(newRequestQueryNestedResponseBodyPager, req)
	if err != nil {
		return nil, err
	}
	if !slices.Contains([]int{http.StatusOK}, resp.StatusCode) {
		p.newRequestQueryNestedResponseBodyPager.remove(req)
		return nil, &nonRetriableError{fmt.Errorf("unexpected status code %d. acceptable values are http.StatusOK", resp.StatusCode)}
	}
	if !server.PagerResponderMore(newRequestQueryNestedResponseBodyPager) {
		p.newRequestQueryNestedResponseBodyPager.remove(req)
	}
	return resp, nil
}

func (p *PageableServerDrivenPaginationContinuationTokenServerTransport) dispatchNewRequestQueryResponseBodyPager(req *http.Request) (*http.Response, error) {
	if p.srv.NewRequestQueryResponseBodyPager == nil {
		return nil, &nonRetriableError{errors.New("fake for method NewRequestQueryResponseBodyPager not implemented")}
	}
	newRequestQueryResponseBodyPager := p.newRequestQueryResponseBodyPager.get(req)
	if newRequestQueryResponseBodyPager == nil {
		qp := req.URL.Query()
		tokenParam := getOptional(qp.Get("token"))
		fooParam := getOptional(getHeaderValue(req.Header, "foo"))
		barParam := getOptional(qp.Get("bar"))
		var options *continuationtoken.PageableServerDrivenPaginationContinuationTokenClientRequestQueryResponseBodyOptions
		if tokenParam != nil || fooParam != nil || barParam != nil {
			options = &continuationtoken.PageableServerDrivenPaginationContinuationTokenClientRequestQueryResponseBodyOptions{
				Token: tokenParam,
				Foo:   fooParam,
				Bar:   barParam,
			}
		}
		resp := p.srv.NewRequestQueryResponseBodyPager(options)
		newRequestQueryResponseBodyPager = &resp
		p.newRequestQueryResponseBodyPager.add(req, newRequestQueryResponseBodyPager)
	}
	resp, err := server.PagerResponderNext(newRequestQueryResponseBodyPager, req)
	if err != nil {
		return nil, err
	}
	if !slices.Contains([]int{http.StatusOK}, resp.StatusCode) {
		p.newRequestQueryResponseBodyPager.remove(req)
		return nil, &nonRetriableError{fmt.Errorf("unexpected status code %d. acceptable values are http.StatusOK", resp.StatusCode)}
	}
	if !server.PagerResponderMore(newRequestQueryResponseBodyPager) {
		p.newRequestQueryResponseBodyPager.remove(req)
	}
	return resp, nil
}

func (p *PageableServerDrivenPaginationContinuationTokenServerTransport) dispatchNewRequestQueryResponseHeaderPager(req *http.Request) (*http.Response, error) {
	if p.srv.NewRequestQueryResponseHeaderPager == nil {
		return nil, &nonRetriableError{errors.New("fake for method NewRequestQueryResponseHeaderPager not implemented")}
	}
	newRequestQueryResponseHeaderPager := p.newRequestQueryResponseHeaderPager.get(req)
	if newRequestQueryResponseHeaderPager == nil {
		qp := req.URL.Query()
		tokenParam := getOptional(qp.Get("token"))
		fooParam := getOptional(getHeaderValue(req.Header, "foo"))
		barParam := getOptional(qp.Get("bar"))
		var options *continuationtoken.PageableServerDrivenPaginationContinuationTokenClientRequestQueryResponseHeaderOptions
		if tokenParam != nil || fooParam != nil || barParam != nil {
			options = &continuationtoken.PageableServerDrivenPaginationContinuationTokenClientRequestQueryResponseHeaderOptions{
				Token: tokenParam,
				Foo:   fooParam,
				Bar:   barParam,
			}
		}
		resp := p.srv.NewRequestQueryResponseHeaderPager(options)
		newRequestQueryResponseHeaderPager = &resp
		p.newRequestQueryResponseHeaderPager.add(req, newRequestQueryResponseHeaderPager)
	}
	resp, err := server.PagerResponderNext(newRequestQueryResponseHeaderPager, req)
	if err != nil {
		return nil, err
	}
	if !slices.Contains([]int{http.StatusOK}, resp.StatusCode) {
		p.newRequestQueryResponseHeaderPager.remove(req)
		return nil, &nonRetriableError{fmt.Errorf("unexpected status code %d. acceptable values are http.StatusOK", resp.StatusCode)}
	}
	if !server.PagerResponderMore(newRequestQueryResponseHeaderPager) {
		p.newRequestQueryResponseHeaderPager.remove(req)
	}
	return resp, nil
}

// set this to conditionally intercept incoming requests to PageableServerDrivenPaginationContinuationTokenServerTransport
var pageableServerDrivenPaginationContinuationTokenServerTransportInterceptor interface {
	// Do returns true if the server transport should use the returned response/error
	Do(*http.Request) (*http.Response, error, bool)
}
