// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package twosubscriptionresourcesmethodlevel

// SubscriptionResource1OperationsClientDeleteOptions contains the optional parameters for the SubscriptionResource1OperationsClient.Delete
// method.
type SubscriptionResource1OperationsClientDeleteOptions struct {
	// placeholder for future optional parameters
}

// SubscriptionResource1OperationsClientGetOptions contains the optional parameters for the SubscriptionResource1OperationsClient.Get
// method.
type SubscriptionResource1OperationsClientGetOptions struct {
	// placeholder for future optional parameters
}

// SubscriptionResource1OperationsClientPutOptions contains the optional parameters for the SubscriptionResource1OperationsClient.Put
// method.
type SubscriptionResource1OperationsClientPutOptions struct {
	// placeholder for future optional parameters
}

// SubscriptionResource2OperationsClientDeleteOptions contains the optional parameters for the SubscriptionResource2OperationsClient.Delete
// method.
type SubscriptionResource2OperationsClientDeleteOptions struct {
	// placeholder for future optional parameters
}

// SubscriptionResource2OperationsClientGetOptions contains the optional parameters for the SubscriptionResource2OperationsClient.Get
// method.
type SubscriptionResource2OperationsClientGetOptions struct {
	// placeholder for future optional parameters
}

// SubscriptionResource2OperationsClientPutOptions contains the optional parameters for the SubscriptionResource2OperationsClient.Put
// method.
type SubscriptionResource2OperationsClientPutOptions struct {
	// placeholder for future optional parameters
}
