// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package internaloperation

// PublicDecoratorModelInInternal - Used in an internal operation but with public decorator, should be generated and exported.
type PublicDecoratorModelInInternal struct {
	// REQUIRED
	Name *string
}

// internalDecoratorModelInInternal - Used in an internal operation, should be generated but not exported.
type internalDecoratorModelInInternal struct {
	// REQUIRED
	Name *string
}

// noDecoratorModelInInternal - Used in an internal operation, should be generated but not exported.
type noDecoratorModelInInternal struct {
	// REQUIRED
	Name *string
}
