// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package contenttype

// MultiPartFormDataHTTPPartsContentTypeClientImageJPEGContentTypeResponse contains the response from method MultiPartFormDataHTTPPartsContentTypeClient.ImageJPEGContentType.
type MultiPartFormDataHTTPPartsContentTypeClientImageJPEGContentTypeResponse struct {
	// placeholder for future response values
}

// MultiPartFormDataHTTPPartsContentTypeClientOptionalContentTypeResponse contains the response from method MultiPartFormDataHTTPPartsContentTypeClient.OptionalContentType.
type MultiPartFormDataHTTPPartsContentTypeClientOptionalContentTypeResponse struct {
	// placeholder for future response values
}

// MultiPartFormDataHTTPPartsContentTypeClientRequiredContentTypeResponse contains the response from method MultiPartFormDataHTTPPartsContentTypeClient.RequiredContentType.
type MultiPartFormDataHTTPPartsContentTypeClientRequiredContentTypeResponse struct {
	// placeholder for future response values
}
