// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package property

import "bytesgroup"

// BytesPropertyClientBase64Response contains the response from method BytesPropertyClient.Base64.
type BytesPropertyClientBase64Response struct {
	bytesgroup.Base64BytesProperty
}

// BytesPropertyClientBase64URLArrayResponse contains the response from method BytesPropertyClient.Base64URLArray.
type BytesPropertyClientBase64URLArrayResponse struct {
	bytesgroup.Base64URLArrayBytesProperty
}

// BytesPropertyClientBase64URLResponse contains the response from method BytesPropertyClient.Base64URL.
type BytesPropertyClientBase64URLResponse struct {
	bytesgroup.Base64URLBytesProperty
}

// BytesPropertyClientDefaultResponse contains the response from method BytesPropertyClient.Default.
type BytesPropertyClientDefaultResponse struct {
	bytesgroup.DefaultBytesProperty
}
