// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package xmlpagination

// PageableXMLPaginationClientListWithContinuationOptions contains the optional parameters for the PageableXMLPaginationClient.NewListWithContinuationPager
// method.
type PageableXMLPaginationClientListWithContinuationOptions struct {
	Marker *string
}

// PageableXMLPaginationClientListWithNextLinkOptions contains the optional parameters for the PageableXMLPaginationClient.NewListWithNextLinkPager
// method.
type PageableXMLPaginationClientListWithNextLinkOptions struct {
	// placeholder for future optional parameters
}
