// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package header

// DurationHeaderClientDefaultOptions contains the optional parameters for the DurationHeaderClient.Default method.
type DurationHeaderClientDefaultOptions struct {
	// placeholder for future optional parameters
}

// DurationHeaderClientFloat64MillisecondsOptions contains the optional parameters for the DurationHeaderClient.Float64Milliseconds
// method.
type DurationHeaderClientFloat64MillisecondsOptions struct {
	// placeholder for future optional parameters
}

// DurationHeaderClientFloat64SecondsOptions contains the optional parameters for the DurationHeaderClient.Float64Seconds
// method.
type DurationHeaderClientFloat64SecondsOptions struct {
	// placeholder for future optional parameters
}

// DurationHeaderClientFloatMillisecondsLargerUnitOptions contains the optional parameters for the DurationHeaderClient.FloatMillisecondsLargerUnit
// method.
type DurationHeaderClientFloatMillisecondsLargerUnitOptions struct {
	// placeholder for future optional parameters
}

// DurationHeaderClientFloatMillisecondsOptions contains the optional parameters for the DurationHeaderClient.FloatMilliseconds
// method.
type DurationHeaderClientFloatMillisecondsOptions struct {
	// placeholder for future optional parameters
}

// DurationHeaderClientFloatSecondsLargerUnitOptions contains the optional parameters for the DurationHeaderClient.FloatSecondsLargerUnit
// method.
type DurationHeaderClientFloatSecondsLargerUnitOptions struct {
	// placeholder for future optional parameters
}

// DurationHeaderClientFloatSecondsOptions contains the optional parameters for the DurationHeaderClient.FloatSeconds method.
type DurationHeaderClientFloatSecondsOptions struct {
	// placeholder for future optional parameters
}

// DurationHeaderClientInt32MillisecondsArrayOptions contains the optional parameters for the DurationHeaderClient.Int32MillisecondsArray
// method.
type DurationHeaderClientInt32MillisecondsArrayOptions struct {
	// placeholder for future optional parameters
}

// DurationHeaderClientInt32MillisecondsLargerUnitOptions contains the optional parameters for the DurationHeaderClient.Int32MillisecondsLargerUnit
// method.
type DurationHeaderClientInt32MillisecondsLargerUnitOptions struct {
	// placeholder for future optional parameters
}

// DurationHeaderClientInt32MillisecondsOptions contains the optional parameters for the DurationHeaderClient.Int32Milliseconds
// method.
type DurationHeaderClientInt32MillisecondsOptions struct {
	// placeholder for future optional parameters
}

// DurationHeaderClientInt32SecondsLargerUnitOptions contains the optional parameters for the DurationHeaderClient.Int32SecondsLargerUnit
// method.
type DurationHeaderClientInt32SecondsLargerUnitOptions struct {
	// placeholder for future optional parameters
}

// DurationHeaderClientInt32SecondsOptions contains the optional parameters for the DurationHeaderClient.Int32Seconds method.
type DurationHeaderClientInt32SecondsOptions struct {
	// placeholder for future optional parameters
}

// DurationHeaderClientIso8601ArrayOptions contains the optional parameters for the DurationHeaderClient.Iso8601Array method.
type DurationHeaderClientIso8601ArrayOptions struct {
	// placeholder for future optional parameters
}

// DurationHeaderClientIso8601Options contains the optional parameters for the DurationHeaderClient.Iso8601 method.
type DurationHeaderClientIso8601Options struct {
	// placeholder for future optional parameters
}
