// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package header

// DurationHeaderClientDefaultResponse contains the response from method DurationHeaderClient.Default.
type DurationHeaderClientDefaultResponse struct {
	// placeholder for future response values
}

// DurationHeaderClientFloat64MillisecondsResponse contains the response from method DurationHeaderClient.Float64Milliseconds.
type DurationHeaderClientFloat64MillisecondsResponse struct {
	// placeholder for future response values
}

// DurationHeaderClientFloat64SecondsResponse contains the response from method DurationHeaderClient.Float64Seconds.
type DurationHeaderClientFloat64SecondsResponse struct {
	// placeholder for future response values
}

// DurationHeaderClientFloatMillisecondsLargerUnitResponse contains the response from method DurationHeaderClient.FloatMillisecondsLargerUnit.
type DurationHeaderClientFloatMillisecondsLargerUnitResponse struct {
	// placeholder for future response values
}

// DurationHeaderClientFloatMillisecondsResponse contains the response from method DurationHeaderClient.FloatMilliseconds.
type DurationHeaderClientFloatMillisecondsResponse struct {
	// placeholder for future response values
}

// DurationHeaderClientFloatSecondsLargerUnitResponse contains the response from method DurationHeaderClient.FloatSecondsLargerUnit.
type DurationHeaderClientFloatSecondsLargerUnitResponse struct {
	// placeholder for future response values
}

// DurationHeaderClientFloatSecondsResponse contains the response from method DurationHeaderClient.FloatSeconds.
type DurationHeaderClientFloatSecondsResponse struct {
	// placeholder for future response values
}

// DurationHeaderClientInt32MillisecondsArrayResponse contains the response from method DurationHeaderClient.Int32MillisecondsArray.
type DurationHeaderClientInt32MillisecondsArrayResponse struct {
	// placeholder for future response values
}

// DurationHeaderClientInt32MillisecondsLargerUnitResponse contains the response from method DurationHeaderClient.Int32MillisecondsLargerUnit.
type DurationHeaderClientInt32MillisecondsLargerUnitResponse struct {
	// placeholder for future response values
}

// DurationHeaderClientInt32MillisecondsResponse contains the response from method DurationHeaderClient.Int32Milliseconds.
type DurationHeaderClientInt32MillisecondsResponse struct {
	// placeholder for future response values
}

// DurationHeaderClientInt32SecondsLargerUnitResponse contains the response from method DurationHeaderClient.Int32SecondsLargerUnit.
type DurationHeaderClientInt32SecondsLargerUnitResponse struct {
	// placeholder for future response values
}

// DurationHeaderClientInt32SecondsResponse contains the response from method DurationHeaderClient.Int32Seconds.
type DurationHeaderClientInt32SecondsResponse struct {
	// placeholder for future response values
}

// DurationHeaderClientIso8601ArrayResponse contains the response from method DurationHeaderClient.Iso8601Array.
type DurationHeaderClientIso8601ArrayResponse struct {
	// placeholder for future response values
}

// DurationHeaderClientIso8601Response contains the response from method DurationHeaderClient.Iso8601.
type DurationHeaderClientIso8601Response struct {
	// placeholder for future response values
}
