// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package xmlbasicgroup

// ModelWithArrayOfModel - Contains an array of models.
type ModelWithArrayOfModel struct {
	// REQUIRED
	Items []SimpleModel `xml:"SimpleModel"`
}

// ModelWithOptionalField - Contains an optional field.
type ModelWithOptionalField struct {
	// REQUIRED
	Item   *string
	Counts *int32
}

// ModelWithSimpleArrays - Contains fields of arrays of primitive types.
type ModelWithSimpleArrays struct {
	// REQUIRED
	Colors []string

	// REQUIRED
	Counts []int32
}

// SimpleModel - Contains fields of primitive types.
type SimpleModel struct {
	// REQUIRED
	Age *int32

	// REQUIRED
	Name *string
}
