// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package uniongroup

type Cat struct {
	Name *string `json:"name"`
}

type Dog struct {
	Bark *string `json:"bark"`
}

type EnumsOnlyCases struct {
	// REQUIRED; This should be receive/send the left variant
	Lr *EnumsOnlyCasesLr

	// REQUIRED; This should be receive/send the up variant
	Ud *EnumsOnlyCasesUd
}

type GetResponse2 struct {
	// REQUIRED
	Prop *StringAndArrayCases
}

type GetResponse4 struct {
	// REQUIRED; The contents of this field are raw JSON.
	Prop []byte
}

type GetResponse7 struct {
	// REQUIRED
	Prop *StringExtensibleNamedUnion
}

type GetResponse8 struct {
	// REQUIRED
	Prop *GetResponseProp4
}

type GetResponse9 struct {
	// REQUIRED
	Prop *GetResponseProp5
}

type MixedLiteralsCases struct {
	// REQUIRED; This should be receive/send the true variant
	BooleanLiteral *bool

	// REQUIRED; This should be receive/send the 3.3 variant
	FloatLiteral *float32

	// REQUIRED; This should be receive/send the 2 variant
	IntLiteral *int32

	// REQUIRED; This should be receive/send the "a" variant
	StringLiteral *string
}

type MixedTypesCases struct {
	// REQUIRED; This should be receive/send 4 element with Cat, "a", int, and boolean
	Array []byte

	// REQUIRED; This should be receive/send the boolean variant
	Boolean []byte

	// REQUIRED; This should be receive/send the int variant
	Int []byte

	// REQUIRED; This should be receive/send the "a" variant
	Literal []byte

	// REQUIRED; This should be receive/send the Cat variant
	Model []byte
}

type StringAndArrayCases struct {
	// REQUIRED; This should be receive/send the array variant
	Array []byte

	// REQUIRED; This should be receive/send the string variant
	String []byte
}
