// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package compute

import (
	"armmultisharedmodelsgroup"
	"armmultisharedmodelsgroup/shared"
)

// VirtualMachine - Describes a Virtual Machine.
type VirtualMachine struct {
	// REQUIRED; The geo-location where the resource lives
	Location *string

	// The resource-specific properties for this resource.
	Properties *VirtualMachineProperties

	// Resource tags.
	Tags map[string]*string

	// READ-ONLY; Fully qualified resource ID for the resource. Ex - /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}
	ID *string

	// READ-ONLY; The name of the resource
	Name *string

	// READ-ONLY; Azure Resource Manager metadata containing createdBy and modifiedBy information.
	SystemData *armmultisharedmodelsgroup.SystemData

	// READ-ONLY; The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts"
	Type *string
}

type VirtualMachineProperties struct {
	// Shared metadata for the virtual machine.
	Metadata *shared.SharedMetadata

	// READ-ONLY
	ProvisioningState *armmultisharedmodelsgroup.ResourceProvisioningState
}
