// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package coreusagegroup

import (
	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
)

// UsageClient - Test for internal decorator.
// Don't use this type directly, use a constructor function instead.
type UsageClient struct {
	internal *azcore.Client
}

// UsageClientOptions contains the optional values for creating a [UsageClient].
type UsageClientOptions struct {
	azcore.ClientOptions
}

// NewUsageClientWithNoCredential creates a new [UsageClient].
//   - options - optional client configuration; pass nil to accept the default values
func NewUsageClientWithNoCredential(options *UsageClientOptions) (*UsageClient, error) {
	if options == nil {
		options = &UsageClientOptions{}
	}
	internal, err := azcore.NewClient(moduleName, moduleVersion, runtime.PipelineOptions{}, &options.ClientOptions)
	if err != nil {
		return nil, err
	}
	return &UsageClient{
		internal: internal,
	}, nil
}

// NewUsageModelInOperationClient creates a new instance of [UsageModelInOperationClient].
func (client *UsageClient) NewUsageModelInOperationClient() *UsageModelInOperationClient {
	return &UsageModelInOperationClient{
		internal: client.internal,
	}
}
