// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package basicparamsgroup

import (
	"basicparamsgroup/explicitbody"
	"basicparamsgroup/implicitbody"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
)

// BasicClient - Test for basic parameters cases.
// Don't use this type directly, use NewBasicClientWithNoCredential() instead.
type BasicClient struct {
	internal *azcore.Client
	endpoint string
}

// BasicClientOptions contains the optional values for creating a [BasicClient].
type BasicClientOptions struct {
	azcore.ClientOptions
}

// NewBasicClientWithNoCredential creates a new instance of BasicClient with the specified values.
//   - endpoint - Service host
//   - options - Contains optional client configuration. Pass nil to accept the default values.
func NewBasicClientWithNoCredential(endpoint string, options *BasicClientOptions) (*BasicClient, error) {
	if options == nil {
		options = &BasicClientOptions{}
	}
	cl, err := azcore.NewClient(moduleName, moduleVersion, runtime.PipelineOptions{}, &options.ClientOptions)
	if err != nil {
		return nil, err
	}
	client := &BasicClient{
		endpoint: endpoint,
		internal: cl,
	}
	return client, nil
}

// NewBasicExplicitBodyClient creates a new instance of [explicitbody.BasicExplicitBodyClient].
func (client *BasicClient) NewBasicExplicitBodyClient() *explicitbody.BasicExplicitBodyClient {
	return &explicitbody.BasicExplicitBodyClient{
		endpoint: client.endpoint,
		internal: client.internal,
	}
}

// NewBasicImplicitBodyClient creates a new instance of [implicitbody.BasicImplicitBodyClient].
func (client *BasicClient) NewBasicImplicitBodyClient() *implicitbody.BasicImplicitBodyClient {
	return &implicitbody.BasicImplicitBodyClient{
		endpoint: client.endpoint,
		internal: client.internal,
	}
}
